import { NextResponse } from "next/server";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

/**
 * Lists the pitch packs generated by scripts/pitch-pack.mjs.
 * Packs live outside the app at ../cards/pitch/<slug>/profile.json, so this only
 * works when the site runs from the repo (local prep machine), which is the point.
 */
export const dynamic = "force-dynamic";

export const PACKS_DIR = path.resolve(process.cwd(), "..", "cards", "pitch");

export async function GET() {
  try {
    const entries = await readdir(PACKS_DIR, { withFileTypes: true });
    const packs = [];
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      try {
        const raw = await readFile(path.join(PACKS_DIR, e.name, "profile.json"), "utf8");
        const p = JSON.parse(raw) as { name?: string; city?: string };
        packs.push({ slug: e.name, name: p.name ?? e.name, city: p.city ?? "" });
      } catch {
        // folder without a readable profile.json; skip
      }
    }
    packs.sort((a, b) => a.name.localeCompare(b.name));
    return NextResponse.json({ packs });
  } catch {
    return NextResponse.json({ packs: [] });
  }
}
